platform :ios, '9.0'

target 'Les Tarots du midi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Les Tarots du midi
  pod 'R.swift'
  pod 'SwiftLint'

end

target 'LTDMapi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LTDMapi

end
